/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BankRouteImport } from './routes/bank'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as BankIdRouteImport } from './routes/bank.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BankRoute = BankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const BankIdRoute = BankIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BankRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bank': typeof BankRouteWithChildren
  '/practice': typeof PracticeRoute
  '/bank/$id': typeof BankIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bank': typeof BankRouteWithChildren
  '/practice': typeof PracticeRoute
  '/bank/$id': typeof BankIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bank': typeof BankRouteWithChildren
  '/practice': typeof PracticeRoute
  '/bank/$id': typeof BankIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bank' | '/practice' | '/bank/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bank' | '/practice' | '/bank/$id'
  id: '__root__' | '/' | '/bank' | '/practice' | '/bank/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BankRoute: typeof BankRouteWithChildren
  PracticeRoute: typeof PracticeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank': {
      id: '/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof BankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank/$id': {
      id: '/bank/$id'
      path: '/$id'
      fullPath: '/bank/$id'
      preLoaderRoute: typeof BankIdRouteImport
      parentRoute: typeof BankRoute
    }
  }
}

interface BankRouteChildren {
  BankIdRoute: typeof BankIdRoute
}

const BankRouteChildren: BankRouteChildren = {
  BankIdRoute: BankIdRoute,
}

const BankRouteWithChildren = BankRoute._addFileChildren(BankRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BankRoute: BankRouteWithChildren,
  PracticeRoute: PracticeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
